version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-73-197-211.compute-1.amazonaws.com
            port: '5432'
            database: d7rrjoqk0a5igs
            ssl: true
            user: iczvzwwyqjpsxl
            password: 9ba6466b1931078968bd1b24d3be8649221fc118f6eefebd2fcb8917a9a7fcff
            migrations: true